name: Build and Push Docker Image

on:
  # DISABLED - Only using release workflow for now
  # This workflow is disabled by using a dummy trigger
  # To re-enable, replace the schedule with the triggers below:
  # push:
  #   branches: [ main ]
  #   paths: [ 'docker/Dockerfile.ci' ]
  # workflow_dispatch:  # Only manual trigger
  
  # Dummy trigger to keep workflow valid (never actually runs)
  schedule:
    - cron: '0 0 1 1 *'  # Runs once a year on Jan 1st (effectively never)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.ci
        push: true
        tags: |
          ghcr.io/spinkoo/pyoctomap/octomap-ci:latest
          ghcr.io/spinkoo/pyoctomap/octomap-ci:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max