name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    paths: [ 'docker/Dockerfile.ci' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile.ci
        push: true
        tags: |
          ghcr.io/spinkoo/octomap2python/octomap-ci:latest
          ghcr.io/spinkoo/octomap2python/octomap-ci:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
