name: Build ROS-Compatible Wheels with Docker

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 0.1.24-ros)'
        required: false
        default: '0.1.24-ros'

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    environment: release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build ROS-compatible wheel with Docker
      run: |
        echo "🚀 Building ROS-compatible wheels using Docker..."
        echo "🐳 Using single Python version (3.11) for faster testing..."
        docker build -f docker/Dockerfile.wheel -t pyoctomap-ros-wheel .
        
        echo "📦 Extracting ROS-compatible wheel from container..."
        docker run --name temp-ros-container pyoctomap-ros-wheel
        docker cp temp-ros-container:/wheels/ ./wheels/
        docker rm temp-ros-container
        
        echo "✅ ROS-compatible wheels built:"
        ls -la wheels/
        
        echo "🔍 Filtering to only manylinux wheels..."
        mkdir -p ./manylinux-wheels
        cp wheels/*manylinux*.whl ./manylinux-wheels/ || echo "No manylinux wheels found"
        echo "🎉 ROS-compatible manylinux wheels:"
        ls -la ./manylinux-wheels/
    
    - name: Upload ROS-compatible wheels
      uses: actions/upload-artifact@v4
      with:
        name: ros-wheel-docker
        path: ./manylinux-wheels

  build-sdist:
    runs-on: ubuntu-latest
    environment: release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Build source distribution
      run: |
        python -m pip install --upgrade pip build
        python -m build --sdist
        echo "✅ Built source distribution:"
        ls -la dist/
    
    - name: Upload source distribution
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  publish:
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-latest
    environment: release
    
    steps:
    - name: Download ROS-compatible wheels
      uses: actions/download-artifact@v4
      with:
        name: ros-wheel-docker
        path: ./wheels
    
    - name: Download source distribution
      uses: actions/download-artifact@v4
      with:
        name: sdist
        path: ./dist
    
    - name: Combine ROS packages for upload
      run: |
        echo "📦 Combining ROS-compatible wheels and source distribution..."
        mkdir -p ./packages
        cp ./wheels/*.whl ./packages/
        cp ./dist/*.tar.gz ./packages/
        echo "🎉 ROS-compatible packages ready for upload:"
        ls -la ./packages/
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: ./packages
        skip_existing: true
