name: Release to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Add manual trigger
    inputs:
      version:
        description: 'Version to release (optional)'
        required: false
        default: ''
      skip_tests:
        description: 'Skip tests (not recommended)'
        required: false
        default: false
        type: boolean

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    environment: release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Display release info
      run: |
        echo "🚀 Building manylinux2014 wheels for broad compatibility"
        echo "🐍 Python version: 3.11"
        if [ -n "${{ github.event.inputs.version }}" ]; then
          echo "📦 Version: ${{ github.event.inputs.version }}"
        fi
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install cibuildwheel
      run: |
        python -m pip install --upgrade pip
        pip install cibuildwheel
    
    - name: Build manylinux2014 wheels
      env:
        CIBW_PLATFORM: linux
        CIBW_BUILD: cp311-manylinux_x86_64
        CIBW_BEFORE_BUILD: |
          if command -v yum >/dev/null 2>&1; then
            yum install -y cmake3 make gcc gcc-c++
            CMAKE_CMD=cmake3
          elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache cmake make gcc g++
            CMAKE_CMD=cmake
          else
            echo "Unknown package manager"
            exit 1
          fi &&
          cd src/octomap && mkdir -p build && cd build &&
          $CMAKE_CMD .. -DCMAKE_BUILD_TYPE=Release &&
          make -j$(nproc) && make install && ldconfig &&
          mkdir -p ../../src/octomap/lib &&
          echo "Copying libraries from $(pwd)/lib to ../../src/octomap/lib" &&
          ls -la lib/ &&
          cp lib/*.so* ../../src/octomap/lib/ 2>/dev/null || echo "No .so files found" &&
          cp lib/*.a ../../src/octomap/lib/ 2>/dev/null || echo "No .a files found" &&
          echo "Libraries copied to ../../src/octomap/lib:" &&
          ls -la ../../src/octomap/lib/
        CIBW_BEFORE_BUILD_LINUX: |
          if command -v yum >/dev/null 2>&1; then
            yum install -y cmake3 make gcc gcc-c++
            CMAKE_CMD=cmake3
          elif command -v apk >/dev/null 2>&1; then
            apk add --no-cache cmake make gcc g++
            CMAKE_CMD=cmake
          else
            echo "Unknown package manager"
            exit 1
          fi &&
          cd src/octomap && mkdir -p build && cd build &&
          $CMAKE_CMD .. -DCMAKE_BUILD_TYPE=Release &&
          make -j$(nproc) && make install && ldconfig &&
          mkdir -p ../../src/octomap/lib &&
          echo "Copying libraries from $(pwd)/lib to ../../src/octomap/lib" &&
          ls -la lib/ &&
          cp lib/*.so* ../../src/octomap/lib/ 2>/dev/null || echo "No .so files found" &&
          cp lib/*.a ../../src/octomap/lib/ 2>/dev/null || echo "No .a files found" &&
          echo "Libraries copied to ../../src/octomap/lib:" &&
          ls -la ../../src/octomap/lib/
      run: |
        echo "Checking if libraries exist before cibuildwheel:"
        ls -la src/octomap/lib/ || echo "No lib directory found"
        cibuildwheel --platform linux --output-dir dist
    
    - name: Upload wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheel-py3.11
        path: dist/*.whl

  build-sdist:
    runs-on: ubuntu-22.04
    environment: release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel numpy cython
    
    - name: Generate PyPI README
      run: |
        python github2pypi/generate_pypi_readme.py
        
        if [ -f "README_pypi_preview.md" ]; then
          echo "✅ PyPI README generated successfully"
        else
          echo "❌ PyPI README generation failed"
          exit 1
        fi
    
    - name: Build source distribution
      run: |
        python setup.py sdist
    
    - name: Upload source distribution
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  publish:
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-22.04
    environment: release
    
    steps:
    - name: Download wheels
      uses: actions/download-artifact@v4
      with:
        name: wheel-py3.11
        path: ./artifacts
    
    - name: Download source distribution
      uses: actions/download-artifact@v4
      with:
        name: sdist
        path: ./artifacts
    
    - name: Organize distributions for publishing
      run: |
        # Create dist directory
        mkdir -p dist
        
        # Copy all wheels to dist directory
        echo "Copying wheels to dist directory:"
        find ./artifacts -name "*.whl" -type f -exec cp {} dist/ \;
        
        # Copy source distributions to dist directory
        echo "Copying source distributions to dist directory:"
        find ./artifacts -name "*.tar.gz" -type f -exec cp {} dist/ \;
        
        # List final distributions
        echo "Final distributions to publish:"
        ls -la dist/
        
        # Verify we have distributions
        if [ -z "$(ls -A dist/)" ]; then
          echo "ERROR: No distributions found in dist/ directory!"
          exit 1
        fi
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: dist/