name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
    
    - name: Build OctoMap C++ library
      run: |
        cd src/octomap
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
        sudo make install
        sudo ldconfig
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine setuptools wheel numpy cython pytest
    
    - name: Build distributions
      run: |
        # Clean any previous builds
        rm -rf build/ dist/ *.egg-info/
        
        # Build using modern build tools that properly read pyproject.toml
        python -m build
        
        # Fix platform tags for PyPI compatibility using auditwheel
        pip install auditwheel
        
        # Create repaired wheels directory
        mkdir -p wheelhouse
        
        # Repair wheels for manylinux compatibility
        for wheel in dist/*.whl; do
          if [[ -f "$wheel" ]]; then
            echo "Repairing wheel: $wheel"
            auditwheel repair "$wheel" -w wheelhouse/ || {
              echo "auditwheel failed, trying manual tag fix..."
              cp "$wheel" wheelhouse/
              cd wheelhouse
              python -c "import os; [os.rename(f, f.replace('linux_x86_64', 'manylinux1_x86_64')) for f in os.listdir('.') if f.endswith('.whl') and 'linux_x86_64' in f]; print('Fixed platform tags')"
              cd ..
            }
          fi
        done
        
        # Replace original wheels with repaired ones
        rm -f dist/*.whl
        cp wheelhouse/*.whl dist/ 2>/dev/null || echo "No wheels to copy"
        
        echo "Final distributions:"
        ls -la dist/
    
    - name: Check distributions
      run: |
        twine check dist/*
        echo "📦 Built distributions:"
        ls -la dist/
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
    
    - name: Create PyPI README artifact
      run: |
        # The github2pypi conversion happens automatically in setup.py
        echo "✅ PyPI README with converted URLs created during build"
    
    - name: Upload PyPI README
      uses: actions/upload-artifact@v4
      with:
        name: pypi-readme
        path: README_PyPI.md
        retention-days: 30