name: Release to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Add manual trigger
    inputs:
      version:
        description: 'Version to release (optional)'
        required: false
        default: ''
      skip_tests:
        description: 'Skip tests (not recommended)'
        required: false
        default: false
        type: boolean

jobs:
  build-wheels:
    runs-on: ubuntu-latest
    environment: release
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Display release info
      run: |
        echo "🚀 Building Linux wheels for Google Colab compatibility"
        echo "🐍 Python version: ${{ matrix.python-version }}"
        if [ -n "${{ github.event.inputs.version }}" ]; then
          echo "📦 Version: ${{ github.event.inputs.version }}"
        fi
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel numpy cython auditwheel
    
    - name: Build OctoMap C++ library for compatibility
      run: |
        cd src/octomap
        mkdir -p build && cd build
        
        # Configure with compatibility flags for older systems
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" \
          -DCMAKE_C_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
        
        make -j$(nproc)
        sudo make install
        sudo ldconfig
        
        echo "✅ OctoMap C++ library built with compatibility flags"
    
    - name: Build wheel with compatibility flags
      run: |
        # Set environment variables for compatibility
        export CFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
        export CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
        export LDFLAGS="-Wl,--as-needed"
        
        python setup.py bdist_wheel
        echo "Built wheel:"
        ls -la dist/*.whl
    
    - name: Check wheel contents and symbols
      run: |
        echo "Checking wheel contents:"
        unzip -l dist/*.whl
        echo "Checking for problematic symbols:"
        auditwheel show dist/*.whl || echo "auditwheel show failed, continuing..."
    
    - name: Repair wheel for Google Colab compatibility
      run: |
        mkdir -p wheelhouse
        echo "🔧 Repairing wheel for Google Colab compatibility..."
        echo "Google Colab requires manylinux1 for maximum compatibility"
        
        # Try manylinux1 first (most compatible with Google Colab)
        auditwheel repair dist/*.whl --plat manylinux1_x86_64 -w wheelhouse/ || {
          echo "manylinux1 failed, trying manylinux2014..."
          auditwheel repair dist/*.whl --plat manylinux2014_x86_64 -w wheelhouse/ || {
            echo "manylinux2014 failed, trying manylinux_2_17..."
            auditwheel repair dist/*.whl --plat manylinux_2_17_x86_64 -w wheelhouse/ || {
              echo "All repair attempts failed, using original wheel"
              cp dist/*.whl wheelhouse/
            }
          }
        }
        
        echo "✅ Final wheels in wheelhouse:"
        ls -la wheelhouse/
        
        # Verify the wheel is compatible
        echo "🔍 Checking wheel compatibility:"
        auditwheel show wheelhouse/*.whl || echo "auditwheel show failed, but wheel exists"
    
    - name: Upload wheel
      uses: actions/upload-artifact@v4
      with:
        name: wheel-py${{ matrix.python-version }}
        path: ./wheelhouse/*.whl

  build-sdist:
    runs-on: ubuntu-latest
    environment: release
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    
    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build setuptools wheel numpy cython
    
    - name: Generate PyPI README
      run: |
        python github2pypi/generate_pypi_readme.py
        
        if [ -f "README_pypi_preview.md" ]; then
          echo "✅ PyPI README generated successfully"
        else
          echo "❌ PyPI README generation failed"
          exit 1
        fi
    
    - name: Build source distribution
      run: |
        python setup.py sdist
    
    - name: Upload source distribution
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  publish:
    needs: [build-wheels, build-sdist]
    runs-on: ubuntu-latest
    environment: release
    
    steps:
    - name: Download all wheels
      uses: actions/download-artifact@v4
      with:
        pattern: wheel-py*
        path: ./artifacts
        merge-multiple: true
    
    - name: Download source distribution
      uses: actions/download-artifact@v4
      with:
        name: sdist
        path: ./artifacts
    
    - name: Organize distributions for publishing
      run: |
        # Create dist directory
        mkdir -p dist
        
        # Copy all wheels to dist directory
        echo "Copying wheels to dist directory:"
        find ./artifacts -name "*.whl" -type f -exec cp {} dist/ \;
        
        # Copy source distributions to dist directory
        echo "Copying source distributions to dist directory:"
        find ./artifacts -name "*.tar.gz" -type f -exec cp {} dist/ \;
        
        # List final distributions
        echo "Final distributions to publish:"
        ls -la dist/
        
        # Verify we have distributions
        if [ -z "$(ls -A dist/)" ]; then
          echo "ERROR: No distributions found in dist/ directory!"
          exit 1
        fi
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: dist/